import { useEffect, useState } from "react";
import { Grid } from "@mui/material";
import Head from "next/head";

// libs
import { fetchStore } from "@/libs/store";

// components
import Layout from "@/components/layout";
import FoodBanner from "@/components/store/FoodBanner";
import CardMenu from "@/components/common/CardMenu";

// pages
import Error from "./_error";

// styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "swiper/css/autoplay";

export default function Home({ store, hasError }) {
	const [storeImages, setStoreImages] = useState([]);
	const [stores, setStores] = useState([]);

	useEffect(() => {
		if (!store) return;
		setStores(store);
	}, []);

	useEffect(() => {
		if (!store) return;
		const images = store.map((s) => s.image);
		setStoreImages(images);
	}, []);

	if (hasError) {
		return <Error statusCode={500} />;
	}

	return (
		<>
			<Head>
				<title>AWESOME FOOD STORE</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Grid>
					<FoodBanner storeImages={storeImages} />
					<CardMenu store={stores} />
				</Grid>
			</Layout>
		</>
	);
}

export const getStaticProps = async () => {
	const store = await fetchStore();
	try {
		return {
			props: {
				store,
			},
		};
	} catch (error) {
		return {
			props: { hasError: true },
		};
	}
};
